# Generated by Django 4.1.5 on 2023-01-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='g_name', max_length=50, verbose_name='group name')),
                ('group_start', models.DateField()),
                ('group_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
