# Generated by Django 4.1.5 on 2023-02-15 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
