# Generated by Django 4.1.5 on 2023-02-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course_group',
        ),
    ]
